MyLeaveCareBot/MyLeaveCareBot/Models/ApplyLeave.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace MyLeaveCareBot.Models
{
    public partial class ApplyLeave
    {
        public int Applyid { get; set; }
        public int? EmpId { get; set; }
        public string LeaveType { get; set; }
        public DateTime LeavestartDate { get; set; }
        public DateTime LeaveEndDate { get; set; }
        public string LeaveReason { get; set; }
        public int? LeaveId { get; set; }
        public int StatusId { get; set; }
        public string Status { get; set; }

        public virtual EmployeeDetail Emp { get; set; }
        public virtual BalanceAvailable Leave { get; set; }
    }
}

MyLeaveCareBot/MyLeaveCareBot/Controllers/ApplyLeavesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyLeaveCareBot.Models;

namespace MyLeaveCareBot.Controllers
{
    public class ApplyLeavesController : Controller
    {
        static readonly log4net.ILog _log4net = log4net.LogManager.GetLogger(typeof(ApplyLeavesController));
        private readonly TestLeaveManagementContext _context;

        public ApplyLeavesController(TestLeaveManagementContext context)
        {
            _context = context;
        }
        public IActionResult EmployeePortal1()
        {


            return View();
        }
        // GET: ApplyLeaves
        public async Task<IActionResult> Index()
        {
            var testLeaveManagementContext = _context.ApplyLeaves.Include(a => a.Emp).Include(a => a.Leave);
            return View(await testLeaveManagementContext.ToListAsync());
        }

        // GET: ApplyLeaves/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applyLeave = await _context.ApplyLeaves
                .Include(a => a.Emp)
                .Include(a => a.Leave)
                .FirstOrDefaultAsync(m => m.Applyid == id);
            if (applyLeave == null)
            {
                return NotFound();
            }

            return View(applyLeave);
        }

        // GET: ApplyLeaves/Create
        public IActionResult Create()
        {
            ViewData["EmpId"] = new SelectList(_context.EmployeeDetails, "EmpId", "EmpId");
            ViewData["LeaveId"] = new SelectList(_context.BalanceAvailables, "LeaveId", "LeaveId");
          //  ViewData["LeaveType"] = new SelectList("Sick Leave","Vacation Leave");
            return View();
        }

        // POST: ApplyLeaves/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Applyid,EmpId,LeaveType,LeavestartDate,LeaveEndDate,LeaveReason,LeaveId,StatusId,Status")] ApplyLeave applyLeave)
        {

            //Not Working as some SSL SOcket Connection Problem
            //using (var httpClient = new HttpClient())
            //{
            //    StringContent content = new StringContent(JsonConvert.SerializeObject(employeeDetail), Encoding.UTF8, "application/json");
            //    using (var response = await httpClient.PostAsync("http://localhost:44349/api/EmployeeDetailsAdd/EmpAdd", content))
            //    {
            //        string apiResponse = await response.Content.ReadAsStringAsync();
            //        EmployeeDetail Emplo = JsonConvert.DeserializeObject<EmployeeDetail>(apiResponse);
            //    }
            //}




            applyLeave.LeaveId = applyLeave.EmpId;
            if (ModelState.IsValid)
            {
                _context.Add(applyLeave);
                await _context.SaveChangesAsync();
                // return RedirectToAction(nameof(Index));
                return RedirectToAction("EmployeePortal","EmployeeManagement");
            }
            ViewData["EmpId"] = new SelectList(_context.EmployeeDetails, "EmpId", "EmpEmail", applyLeave.EmpId);
            ViewData["LeaveId"] = new SelectList(_context.BalanceAvailables, "LeaveId", "LeaveId", applyLeave.LeaveId);
            return View(applyLeave);
        }

        // GET: ApplyLeaves/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applyLeave = await _context.ApplyLeaves.FindAsync(id);
            if (applyLeave == null)
            {
                return NotFound();
            }
            ViewData["EmpId"] = new SelectList(_context.EmployeeDetails, "EmpId", "EmpName", applyLeave.EmpId);
            ViewData["LeaveId"] = new SelectList(_context.BalanceAvailables, "LeaveId", "LeaveId", applyLeave.LeaveId);
            return View(applyLeave);
        }

        // POST: ApplyLeaves/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Applyid,EmpId,LeaveType,LeavestartDate,LeaveEndDate,LeaveReason,LeaveId,StatusId,Status")] ApplyLeave applyLeave)
        {
            if (id != applyLeave.Applyid)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(applyLeave);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ApplyLeaveExists(applyLeave.Applyid))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpId"] = new SelectList(_context.EmployeeDetails, "EmpId", "EmpEmail", applyLeave.EmpId);
            ViewData["LeaveId"] = new SelectList(_context.BalanceAvailables, "LeaveId", "LeaveId", applyLeave.LeaveId);
            return View(applyLeave);
        }

        // GET: ApplyLeaves/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var applyLeave = await _context.ApplyLeaves
                .Include(a => a.Emp)
                .Include(a => a.Leave)
                .FirstOrDefaultAsync(m => m.Applyid == id);
            if (applyLeave == null)
            {
                return NotFound();
            }

            return View(applyLeave);
        }

        // POST: ApplyLeaves/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var applyLeave = await _context.ApplyLeaves.FindAsync(id);
            _context.ApplyLeaves.Remove(applyLeave);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ApplyLeaveExists(int id)
        {
            return _context.ApplyLeaves.Any(e => e.Applyid == id);
        }
       
    }
}

MyLeaveCareBot/MyLeaveCareBot/Views/ApplyLeaves/Create.cshtml
@model MyLeaveCareBot.Models.ApplyLeave

@{
    ViewData["Title"] = "Create";
}



<h4>Apply Leave</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpId" class="control-label"></label>
                <select asp-for="EmpId" class="form-control" asp-items="ViewBag.EmpId"></select>
            </div>
            <div class="form-group">
                <label asp-for="LeaveType" class="control-label"></label>
                <select asp-for="LeaveType" class="form-control">
                    <option value="Sick Leave">Sick Leave</option>
                    <option value="Vacation Leave">Vacation Leave</option>
                    <option value="Covid-19">Covid-19</option>
                </select>

            </div>
            <div class="form-group">
                <label asp-for="LeavestartDate" class="control-label"></label>
                <input asp-for="LeavestartDate" class="form-control" />
                <span asp-validation-for="LeavestartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveEndDate" class="control-label"></label>
                <input asp-for="LeaveEndDate" class="form-control" />
                <span asp-validation-for="LeaveEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveReason" class="control-label"></label>
                <input asp-for="LeaveReason" class="form-control" />
                <span asp-validation-for="LeaveReason" class="text-danger"></span>
            </div>
            

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="EmployeePortal1" asp-controller="EmployeeManagement">Back to Portal</a>
</div>

MyLeaveCareBot/MyLeaveCareBot/Views/ApplyLeaves/Delete.cshtml
@model MyLeaveCareBot.Models.ApplyLeave

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplyLeave</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeavestartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeavestartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveReason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveReason)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emp.EmpEmail)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leave.LeaveId)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Applyid" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MyLeaveCareBot/MyLeaveCareBot/Views/ApplyLeaves/Details.cshtml
@model MyLeaveCareBot.Models.ApplyLeave

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ApplyLeave</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeavestartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeavestartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveEndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveEndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveReason)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LeaveReason)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StatusId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StatusId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Emp)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Emp.EmpEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leave)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leave.LeaveId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Applyid">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

MyLeaveCareBot/MyLeaveCareBot/Views/ApplyLeaves/Edit.cshtml
@model MyLeaveCareBot.Models.ApplyLeave

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>ApplyLeave</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Applyid" />
            <div class="form-group">
                <label asp-for="EmpId" class="control-label"></label>
                <select asp-for="EmpId" class="form-control" asp-items="ViewBag.EmpId"></select>
                <span asp-validation-for="EmpId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveType" class="control-label"></label>
                <input asp-for="LeaveType" class="form-control" />
                <span asp-validation-for="LeaveType" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeavestartDate" class="control-label"></label>
                <input asp-for="LeavestartDate" class="form-control" />
                <span asp-validation-for="LeavestartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveEndDate" class="control-label"></label>
                <input asp-for="LeaveEndDate" class="form-control" />
                <span asp-validation-for="LeaveEndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeaveReason" class="control-label"></label>
                <input asp-for="LeaveReason" class="form-control" />
                <span asp-validation-for="LeaveReason" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select asp-for="Status" class="form-control">
                    <option value="Approved">Approved</option>
                    <option value="Rejected">Rejected</option>
                  </select>
               <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MyLeaveCareBot/MyLeaveCareBot/Views/ApplyLeaves/EmployeePortal1.cshtml
@model MyLeaveCareBot.Models.EmployeeDetail
@{
    ViewData["Title"] = "EmployeePortal1";
}

<h3>Employee Portal Welcome</h3>
<style>
    body {
        background-image: url('https://encrypted-tbn0.gstatic.com/images?q=tbn%3AANd9GcSPU-QIMpCmFXk4LqFbEGgtMdwWmAEXGiIMGA&usqp=CAU');
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: 150% 150%;
    }
</style>
<nav class="navbar navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <i class="fa fa-cubes" aria-hidden="true"></i>
        Employee Portal
    </a>
    <ul class="nav nav-pills">
        <li class="nav-item ">
            <button class="badge-light">   <a asp-action="Create" asp-controller="ApplyLeaves">Apply Leave</a> </button>
        </li>
        <li class="nav-item">
            <button class="badge-light">   <a asp-action="Index" asp-controller="ApplyLeaves">See My Status</a> </button>
        </li>

    </ul>
</nav>

MyLeaveCareBot/MyLeaveCareBot/Views/ApplyLeaves/Index.cshtml
@model IEnumerable<MyLeaveCareBot.Models.ApplyLeave>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>

    <a asp-action="HRPortal" asp-controller="HRManagement">Back to HR Portal</a>
    <a asp-action="EmployeePortal1" asp-controller="ApplyLeaves">Back to Employee Portal</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Emp.EmpName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeavestartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveEndDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LeaveReason)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emp.EmpEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Emp.EmpId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Emp.EmpName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeavestartDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveEndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LeaveReason)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Emp.EmpEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Emp.EmpId)
            </td>
            <td>
                <a asp-action="Edit" asp-controller="ApplyLeaves" asp-route-id="@item.Applyid">Update Status</a>||
                <a asp-action="Delete" asp-controller="ApplyLeaves" asp-route-id="@item.Applyid">Delete</a>

            </td>
        </tr>
}
    </tbody>
</table>